---
title: "Mass spec analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mass spec data analysis

Limma-based analysis: 
https://www.sciencedirect.com/science/article/pii/S2212968515000069
https://www.biostat.jhsph.edu/~kkammers/software/eupa/R_guide.html

Load required packages
```{r}
library(readxl)
library(dplyr)
library(data.table)
library(reshape2)
library(limma)
library(MASS)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(ggh4x)
library(scales)
source("functions_mass_spec.R")
```

## Run functions

```{r C-terminal}
mass_spec_data <- consolidate(filepath = "../../Processed data/Mass spec/Mass spectrometry C-terminal data.xlsx")

ibaq <- list()
ibaq[["UPF1-FLAG"]] <- ave_nonzero_combine(dat = mass_spec_data, Total_col = c(14, 2, 4), IP_col = c(15, 3, 5), minrep = 2)
ibaq[["UPF1-FLAG/upf2Δ"]] <- ave_nonzero_combine(dat = mass_spec_data, Total_col = c(12, 16, 18), IP_col = c(13, 17, 19), minrep = 2)
ibaq[["DE572AA-FLAG"]] <- ave_nonzero_combine(dat = mass_spec_data, Total_col = c(10, 6, 8), IP_col = c(11, 7, 9), minrep = 2)

# Run eb_fit for differential expression
DE_Cterm <- lapply(ibaq, function(x) {xx <- x$separate; y <- eb_fit(xx); return(y)})
save(DE_Cterm, file = "eb_fit_Cterm.Rdata")

# For volcano plot
VP_Cterm <- bind_rows(lapply(DE_Cterm, function(x) {xx <- x$eb_fit_res; return(xx)}), .id = "sample")

# For scatter plot
SP_Cterm <- bind_rows(lapply(ibaq, function(x) {xx <- x$average; return(xx)}), .id = "sample")
```

```{r FLAG-UPF1}
mass_spec_data <- consolidate(filepath = "../../Processed data/Mass spec/Mass spectrometry FLAG-Upf1.xlsx")

ibaq <- list()
ibaq[["FLAG-UPF1 (-CHX)"]] <- ave_nonzero_combine(dat = mass_spec_data, Total_col = c(3, 5), IP_col = c(7, 9), minrep = 2)
ibaq[["FLAG-UPF1 (+CHX)"]] <- ave_nonzero_combine(dat = mass_spec_data, Total_col = c(2, 4), IP_col = c(6, 8), minrep = 2)

# Run eb_fit for differential expression
DE_Nterm <- lapply(ibaq, function(x) {xx <- x$separate; y <- eb_fit(xx); return(y)})
save(DE_Nterm, file = "eb_fit_FLAG-UPF1.Rdata")

# For volcano plot
VP_Nterm <- bind_rows(lapply(DE_Nterm, function(x) {xx <- x$eb_fit_res; return(xx)}), .id = "sample")

# For scatter plot
SP_Nterm <- bind_rows(lapply(ibaq, function(x) {xx <- x$average; return(xx)}), .id = "sample")
```

```{r Triple overexpression}
mass_spec_data <- consolidate(filepath = "../../Processed data/Mass spec/Mass spectrometry FLAG-Upf1 Upf2-Upf3 EE data.xlsx")

ibaq <- list()
ibaq[["FLAG-UPF1 UPF2/3 EE"]] <- ave_nonzero_combine(dat = mass_spec_data, Total_col = c(2, 4), IP_col = c(3, 5), minrep = 2)

# Run eb_fit for differential expression
DE_OE3 <- lapply(ibaq, function(x) {xx <- x$separate; y <- eb_fit(xx); return(y)})
save(DE_OE3, file = "eb_fit_OE3.Rdata")

# For volcano plot
VP_OE3 <- bind_rows(lapply(DE_OE3, function(x) {xx <- x$eb_fit_res; return(xx)}), .id = "sample")

# For scatter plot
SP_OE3<- bind_rows(lapply(ibaq, function(x) {xx <- x$average; return(xx)}), .id = "sample")
```

```{r 6XHis-UPF1}
mass_spec_data <- consolidate(filepath = "../../Processed data/Mass spec/Mass spectrometry 6XHis-Upf1 data.xlsx")

ibaq_pass <- mass_spec_data[rowSums(mass_spec_data[, 2:3]) > 0, ]
colnames(ibaq_pass) <- c("Protein", "Total", "IP")
ibaq_pass[ibaq_pass == 0] <- NA

# Emulate results of other strains
DE_His <- list()
DE_His[["6XHis-UPF1"]] <- list()
DE_His[["6XHis-UPF1"]]$IP_exclusive <- ibaq_pass[is.na(ibaq_pass$Total), ]
DE_His[["6XHis-UPF1"]]$Total_exclusive <- ibaq_pass[is.na(ibaq_pass$IP), ]
DE_His[["6XHis-UPF1"]]$filtered <- ibaq_pass[!(ibaq_pass$Protein %in% c(DE_His[["6XHis-UPF1"]]$Total_exclusive$Protein, 
                                                                        DE_His[["6XHis-UPF1"]]$IP_exclusive$Protein)), ]
save(DE_His, file = "eb_fit_6xHis-FLAG.Rdata")

# For scatter plot
SP_His <- ibaq_pass
SP_His$sample <- "6XHis-UPF1"
```

```{r}
save(VP_Cterm, VP_Nterm, VP_OE3, file = "Mass_spec_VP_all.Rdata")
save(SP_Cterm, SP_Nterm, SP_OE3, SP_His, file = "Mass_spec_SP_all.Rdata")
```

## Plots

### Volcano plot
of IP iBAQs vs. Total IBAQs, with p-value
```{r}
load("Mass_spec_VP_all.Rdata")
res_df <- bind_rows(list(VP_Cterm, VP_Nterm, VP_OE3))
res_df <- label_protein(res_df) # Specify protein groups and proteins to be labeled

res_df$sample <- recode_factor(res_df$sample, `FLAG-UPF1 (-CHX)` = "FLAG-UPF1 (-CHX)", `FLAG-UPF1 (+CHX)` = "FLAG-UPF1 (+CHX)",
                               `FLAG-UPF1_UPF2_UPF3_EE` = "FLAG-UPF1 UPF2/3 EE (+CHX)", `UPF1-FLAG` = "UPF1-FLAG (+CHX)", 
                               `UPF1-FLAG_upf2del` = "UPF1-FLAG/upf2Δ (+CHX)", `DE572AA-FLAG` = "DE572AA-FLAG (+CHX)")

# Additional label
tryCatch({res_df[which(res_df$Protein == "RPP2A"), ]$repel <- "Rpp2A"}, error = function(e){})
tryCatch({res_df[which(res_df$Protein == "RPP2B"), ]$repel <- "Rpp2B"}, error = function(e){})
```
```{r}
pvolcano <- ggplot() +
  # Other (uncategorized proteins)
  geom_point(data = res_df[res_df$Protein2 == "Other", ], 
             aes(x = logFC, y = -log10(adj.P.Val)), alpha = 0.5, color = "grey60", size = 0.7) +
  # Categorized
  geom_point(data = res_df[res_df$Protein2 != "Other", ], 
             aes(x = logFC, y = -log10(adj.P.Val), color = Protein2), alpha = 0.8, size = 0.7) +
  # Proteins to label
  geom_point(data = res_df[res_df$repel != "", ], 
             aes(x = logFC, y = -log10(adj.P.Val), color = Protein2), alpha = 1, size = 0.7) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "grey50") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey50") +
  geom_label_repel(data = res_df, 
             aes(x = logFC, y = -log10(adj.P.Val), color = Protein2, label = repel), alpha = 1, size = 8/.pt,
             show.legend = FALSE, max.overlaps = Inf, min.segment.length = 0, box.padding = 0.2, segment.size = 0.25, hjust = 0.5, 
             direction = "both", point.padding = 0, label.padding = 0.1) +
  facet_wrap(~sample, nrow = 2) +
  scale_color_manual(name = "",
                     values = c(Upf1 = "red", Upf2 = "darkorange", Upf3 = "darkgreen",`Ribosomal protein` = "dodgerblue", 
                                `Translation initiation factor` = "darkblue", `Translation elongation factor` = "darkviolet",
                                `Translation termination factor` = "limegreen", `mRNA decay factor` = "brown", 
                                `Protein folding chaperone` = "gold", Other = "grey60")) +
  xlab(expression("log"[2]*"(IP / Total)")) + ylab(expression("-log"[10]*"(adjusted p-value)")) +
  coord_cartesian(clip = "off") +
  theme_bw(base_size = 10) + 
  theme(panel.grid = element_blank(), strip.background = element_blank(), strip.text = element_text(face = "italic"),
        legend.position = "bottom", legend.key.width = unit(0.1, "cm"), 
        legend.text = element_text(margin = margin(r = 0.5, unit = "cm"))) +
  guides(colour = guide_legend(title = NULL, byrow = FALSE, override.aes = list(size = 1)), 
         alpha = guide_legend(override.aes = list(alpha = 1)),
         shape = "none")
```

### Scatter plot
of Total iBAQs vs. IP iBAQs
```{r}
load("Mass_spec_SP_all.Rdata")
dfs <- bind_rows(list(SP_Cterm, SP_Nterm, SP_OE3, SP_His))
dfs <- label_protein(dfs) # Specify protein groups and proteins to be labeled
dfs[is.na(dfs)] <- 0 # Replace NA with 0
dfs <- dfs[which(dfs$IP > 0 | dfs$Total > 0), ] # Exclude proteins that's 0 for both IP and Total

dfs$sample <- recode_factor(dfs$sample, `FLAG-UPF1 (-CHX)` = "FLAG-UPF1 (-CHX)", `FLAG-UPF1 (+CHX)` = "FLAG-UPF1 (+CHX)",
                            `FLAG-UPF1 UPF2/3 EE` = "FLAG-UPF1 UPF2/3 EE (+CHX)", `6XHis-UPF1` = "6XHis-UPF1 (+CHX)",
                            `UPF1-FLAG` = "UPF1-FLAG (+CHX)", 
                            `UPF1-FLAG/upf2Δ` = "UPF1-FLAG/upf2Δ (+CHX)", `DE572AA-FLAG` = "DE572AA-FLAG (+CHX)")

# Additional label
tryCatch({dfs[which(dfs$Protein == "RPP2A"), ]$repel <- "Rpp2A"}, error = function(e){})
tryCatch({dfs[which(dfs$Protein == "RPP2B"), ]$repel <- "Rpp2B"}, error = function(e){})
```
```{r}
pscatter <- ggplot() +
  # Other (uncategorized proteins)
  geom_point(data = dfs[dfs$Protein2 == "Other", ], 
             aes(x = log10(Total), y = log10(IP)), alpha = 0.5, color = "grey60", size = 0.7) +
  # Categorized
  geom_point(data = dfs[dfs$Protein2 != "Other", ], 
             aes(x = log10(Total), y = log10(IP), color = Protein2), alpha = 0.8, size = 0.7) +
  # Proteins to label
  geom_point(data = dfs[dfs$repel != "", ], 
             aes(x = log10(Total), y = log10(IP), color = Protein2), alpha = 1, size = 0.7) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "grey50") +
  geom_label_repel(data = dfs, 
             aes(x = log10(Total), y = log10(IP), color = Protein2, label = repel), alpha = 1, size = 8/.pt,
             show.legend = FALSE, max.overlaps = Inf, min.segment.length = 0, box.padding = 0.2, segment.size = 0.25, hjust = 0.5, 
             direction = "both", point.padding = 0, label.padding = 0.1) +
  facet_wrap(~sample, ncol = 4) +
  scale_color_manual(name = "", #limits = c("Upf1", "Upf2", "Upf3", "Ribosomal protein", "Other"),
                     values = c(Upf1 = "red", Upf2 = "darkorange", Upf3 = "darkgreen",`Ribosomal protein` = "dodgerblue", 
                                `Translation initiation factor` = "darkblue", `Translation elongation factor` = "darkviolet",
                                `Translation termination factor` = "limegreen", `mRNA decay factor` = "brown", 
                                `Protein folding chaperone` = "gold", Other = "grey60")) +
  xlab(expression("log"[10]*"(Total)")) + ylab(expression("log"[10]*"(IP)")) +
  coord_cartesian(xlim = c(4, 10.7), ylim = c(4, 10.7), clip = "off") +
  theme_bw(base_size = 10) + 
  theme(panel.grid = element_blank(), strip.background = element_blank(), strip.text = element_text(face = "italic"),
        legend.position = "none") +  
  guides(colour = guide_legend(title = NULL, byrow = FALSE, override.aes = list(size = 1), nrow = 3), 
         alpha = guide_legend(override.aes = list(alpha = 1)))
```

### Combine scatter and volcano plots

```{r}
library(patchwork)
library(ggpubr)

pv <- pvolcano + theme(legend.position = "none") + plot_spacer() + plot_layout(widths = c(3.1, 0.9), nrow = 1)
pleg <- get_legend(pvolcano)
psv <- ggarrange(pscatter, pv, pleg, 
                 ncol = 1, nrow = 3, heights = c(1, 1, 0.1),
                 labels = c("A", "B", ""), font.label = list(size = 12, face = "bold"))

# Export plot
library(Cairo)
CairoFonts(
  regular = "Arial:style=Regular",
  bold = "Arial:style=Black",
  italic = "Arial:style=Italic",
  bolditalic = "Arial:style=Black Italic",
  symbol = "Symbol"
)
cairo_pdf(filename = "Mass_spec_scatter_volcano_7.5x9.5.pdf", family = "Arial", width = 7.5, height = 9.5) 
psv
dev.off()
```


### Bar plot
of top 100 (or other specified number) iBAQs in each sample's Total and IP
```{r}
load("Mass_spec_SP_all.Rdata")
dfs <- bind_rows(list(SP_Cterm, SP_Nterm, SP_OE3, SP_His))

tops <- function(df, n = 100, value_column = "Total") {
  colnames(df)[which(colnames(df) == value_column)] <- "value"
  df <- df[, c("sample", "Protein", "value")]
  df_list <- split(df, f = df$sample)
  top_list <- list()
  for(i in 1:length(df_list)) {
    top_list[[i]] <- df_list[[i]][order(df_list[[i]]$value, decreasing = TRUE), ]
    top_list[[i]] <- top_list[[i]][1:n, ]
    top_list[[i]]$Protein <- factor(top_list[[i]]$Protein, levels = top_list[[i]]$Protein[order(top_list[[i]]$value, decreasing = TRUE)])
    top_list[[i]]$plot_order <- c(seq(1:n))
    top_list[[i]]$ribosome <- value_column
  }
  names(top_list) <- names(df_list)
  top_df <- bind_rows(top_list, .id = "sample")
  return(top_df)
}

tops100 <- rbind(tops(df = dfs, n = 100, value_column = "Total"), tops(df = dfs, n = 100, value_column = "IP"))
tops100 <- label_protein(tops100) # Specify protein groups and proteins to be labeled
tops100$sample <- recode_factor(tops100$sample, `FLAG-UPF1 (-CHX)` = "FLAG-UPF1 (-CHX)", `FLAG-UPF1 (+CHX)` = "FLAG-UPF1 (+CHX)",
                                `FLAG-UPF1 UPF2/3 EE` = "FLAG-UPF1 UPF2/3 EE (+CHX)", `6XHis-UPF1` = "6XHis-UPF1 (+CHX)",
                                `UPF1-FLAG` = "UPF1-FLAG (+CHX)", 
                                `UPF1-FLAG/upf2Δ` = "UPF1-FLAG/upf2Δ (+CHX)", `DE572AA-FLAG` = "DE572AA-FLAG (+CHX)")
tops100$ribosome <- factor(tops100$ribosome, levels = c("Total", "IP"))
```
```{r}
# https://community.rstudio.com/t/formatting-the-x-axis-with-exponent-values-in-r-plot/34055/3
# https://stackoverflow.com/questions/10762287/how-can-i-format-axis-labels-with-exponents-with-ggplot2-and-scales
scientific_10 <- function(x) {
  parse(text = gsub("[+]", "", gsub("e", " %*% 10^", scales::scientific_format()(x))))
}

protein_colors <- c(Upf1 = "red", Upf2 = "darkorange", Upf3 = "darkgreen",`Ribosomal protein` = "dodgerblue", 
                    `Translation initiation factor` = "darkblue", `Translation elongation factor` = "darkviolet",
                    `Translation termination factor` = "limegreen", `mRNA decay factor` = "brown", 
                    `Protein folding chaperone` = "gold", Other = "grey60")

bar_plot <- function(df2, y_breaks = seq(0, 10*10^9, 1*10^9), legend_pos = "bottom") {
  axis_range <- ((max(df2$value)/10^9 - min(df2$value)/10^9)*10^9)
  p <- ggplot() +
    geom_col(data = df2,
             aes(x = plot_order, y = value, fill = Protein2), color = NA, width = 1, alpha = 1) +
    geom_segment(data = df2[df2$Protein2 %in% c("Upf1"), ], 
                 aes(x = plot_order, y = value + (axis_range*0.4), 
                     xend = plot_order, yend = value + (axis_range*0.1), color = Protein2), 
                 arrow = arrow(length = unit(0.1, "cm"))) +
    facet_grid(ribosome~sample) +
    scale_fill_manual(name = "", #limits = c("Upf1", "Upf2", "Upf3", "Ribosomal protein", "Other"),
                      values = protein_colors) +
    scale_color_manual(name = "", limits = c("Upf1"), guide = "none", values = protein_colors) +
    scale_y_continuous(labels = scientific_10, breaks = y_breaks) + # N-term
    ylab("Ave. Normalized iBAQ") + xlab("100 most abundant proteins") +
    theme_bw(base_size = 10) + 
    theme(panel.grid = element_blank(), strip.background = element_rect(fill = "white"), strip.text.x = element_text(face = "italic"),
          axis.text.x = element_blank(), axis.ticks.x = element_blank(), legend.position = legend_pos)
  return(p)
}

np <- bar_plot(df2 = tops100[which(tops100$sample %in% c("FLAG-UPF1 (-CHX)", "FLAG-UPF1 (+CHX)", "FLAG-UPF1 UPF2/3 EE (+CHX)")), ], 
               y_breaks = seq(0, 10*10^9, 1*10^9), legend_pos = "none")
cp <- bar_plot(df2 = tops100[which(tops100$sample %in% c("UPF1-FLAG (+CHX)", "UPF1-FLAG/upf2Δ (+CHX)", "DE572AA-FLAG (+CHX)")), ], 
               y_breaks = seq(0, 2*10^10, 2*10^9), legend_pos = "none")
hp <- bar_plot(df2 = tops100[which(tops100$sample %in% c("6XHis-UPF1 (+CHX)")), ], 
               y_breaks = seq(0, 10*10^10, 10*10^9), legend_pos = "right")

```
```{r}
library(patchwork)
#pb <- np + hp + cp + guide_area() + plot_layout(ncol = 2, widths = c(3, 1), guides = "collect")
pb <- np + hp + theme(axis.title.y = element_blank()) + cp + guide_area() + plot_layout(ncol = 2, widths = c(3.1, 0.9), guides = "collect")

# Export plot
library(Cairo)
CairoFonts(
  regular = "Arial:style=Regular",
  bold = "Arial:style=Black",
  italic = "Arial:style=Italic",
  bolditalic = "Arial:style=Black Italic",
  symbol = "Symbol"
)
cairo_pdf(filename = "Mass_spec_bar_top100_8.5x7.pdf", family = "Arial", width = 8.5, height = 7) 
pb
dev.off()
```


## Export data into csv files

```{r}
export_data <- function(data_list, sample_name) {
  ibaqs <- bind_rows(data_list[1:3], .id = "Detection")
  ibaqs$Detection <- recode(ibaqs$Detection, filtered = "Detected_in_both")
  write.csv(ibaqs, file = paste0("./export_data/", sample_name, "_filtered_iBAQ_values.csv"), row.names = FALSE)
  if (length(data_list) == 4) {
    eb <- data_list[[4]]
    write.csv(eb, file = paste0("./export_data/", sample_name, "_limma_abundance_changes.csv"), row.names = FALSE)
  }
}
```
```{r}
sapply(names(DE_Nterm), function(x) export_data(DE_Nterm[[x]], x))

names(DE_Cterm)[2] <- "UPF1-FLAG_upf2del" # had to change name because delta sign and slash give errors
sapply(names(DE_Cterm), function(x) export_data(DE_Cterm[[x]], x))

names(DE_OE3) <- "FLAG-UPF1_UPF2_UPF3_EE" # had to change name because slash gives error
sapply(names(DE_OE3), function(x) export_data(DE_OE3[[x]], x))

sapply(names(DE_His), function(x) export_data(DE_His[[x]], x))
```
